apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rgf1tw9k1-java-quarkus
  janus-idp.io/tekton: rgf1tw9k1-java-quarkus
  backstage.io/kubernetes-id: rgf1tw9k1-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rgf1tw9k1-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
